injectables:
  - name: messagePrinterC
    package: inject
    params: 
      Message: "This message is from configuration file - qa"
      Count: 5

interfaces:
  - name: iMessagePrinter
    injectable: messagePrinterC
    package: inject