injectables:
  - name: messagePrinterE
    package: inject 
  - name: messagePrinterD
    package: inject
    params: ["Message and data from config dev file", "boolean:", true, "number:", 12.34] 
  - name: messagePrinterB
    package: inject
    mode: auto
    params: "This message is from configuration file - dev - from messagePrinterB instance"

interfaces:
  - name: iMessagePrinter
    injectable: messagePrinterD
    package: inject