injectables:
  - name: messagePrinterB
    package: main
    params: "This message is from configuration file - prod"

interfaces:
  - name: iMessagePrinter
    injectable: messagePrinterB
    package: main